### ISSUE TITLE
Website todo list from readme page

### ISSUE THREAD

**Issue by susheel** [ga4gh-beacon/ga4gh-beacon-legacy-website#19]
## To do
- [x] Make .md pages for rest of site and import content
- [ ] Review Javascript - remove unnecessary js
- [ ] Create SASS files and directory?
- [x] Check fontawesome integration
- [ ] Use Font Awesome CDN instead?
- [ ] Check for errors in the console and terminal (on file generation)
- [ ] Check responsiveness, including mobile menu
- [ ] Use posts for news and events?
- [ ] Create JSON file for Chairs (find out who they are)
- [ ] Do we need a 'Developers' page? (There is `developers.json` in `_data` in case.)
- [ ] Rename 'News' 'News & Events'?
- [ ] Add footer contact and Twitter info
- [ ] Extract page front matter into config.yml

**Comment by mbaudis** [comment]
Different structure now; some of the points still stand. But stale - closing.
